#!/usr/bin/awk -f
BEGIN {FS="::";
      fmt="<li><a href='%s'>%s</a></li>\n"
      nat="http://natura.di.uminho.pt/~jj/ARQEVO/"
      header="<html><head><meta charset='UTF-8'/></head><body>"
      print header > "index.html"
      print "<h1>Arquivo sonoro evo>/h1>" > "index.html"
}

!m[$1] {printf fmt, $1".html", $1 > "index.html" 
		m[$1]++
		print header > $1".html"
		print "<h1>" $1 "</h1>" > $1".html"
	   }
	   {printf fmt, nat $(NF-1), $3 > $1".html"}
	   {split ($5, i, "[;,] *");
	   for(a in i){ print a, i[a]
	   			    ii[i[a]]=ii[i[a]] > sprintf(fmt, nat $(NF-1), $3)
	   			  }
	   }
END{for(x in ii){
	    print x, ii[x] > "indice_instrumentos.html"
}
	for(y in m){
		print "</body></html>" >y".html"
	}
}